# Generated by Django 2.2.5 on 2019-10-29 08:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('watchlist', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default='')),
            ],
        ),
    ]
