# Generated by Django 2.2.5 on 2019-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsh_user', '0002_auto_20191029_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='price',
            field=models.FloatField(default=''),
        ),
    ]
