# Generated by Django 2.2.5 on 2019-12-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsh_user', '0003_auto_20191030_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.CharField(default='Explore Stocks and Add them to your watchlist', max_length=300),
        ),
    ]
