# Generated by Django 2.2.4 on 2019-10-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Conames',
        ),
    ]
