# Generated by Django 2.2.5 on 2019-11-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_analysis', '0002_auto_20191003_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='conames',
            name='tick',
            field=models.CharField(default='nil', max_length=300),
            preserve_default=False,
        ),
    ]
