# Generated by Django 2.2.5 on 2019-11-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_analysis', '0004_auto_20191119_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conames',
            name='tick',
        ),
    ]
