# Generated by Django 2.2.5 on 2019-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_analysis', '0005_remove_conames_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='conames',
            name='tick',
            field=models.CharField(default='', max_length=300),
        ),
    ]
