# Generated by Django 2.2.5 on 2019-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hco_name', models.CharField(default='', max_length=300)),
                ('htic_name', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
