# Generated by Django 2.2.5 on 2019-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_db',
            name='hco_logo',
            field=models.ImageField(default='', height_field=5, upload_to='', width_field=5),
        ),
    ]
