# Generated by Django 2.2.5 on 2019-12-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_db_hco_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_db',
            name='hco_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
